# Generated by Django 4.1.4 on 2022-12-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtype', models.CharField(blank=True, max_length=100)),
                ('text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
